# Generated by Django 4.2.1 on 2023-05-04 14:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('referencia', models.CharField(max_length=15, verbose_name='Referencia')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion artículo')),
                ('precio_bruto', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Precio sin impuestos')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.21, max_digits=3)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
            },
        ),
    ]
