# Generated by Django 4.2.1 on 2023-05-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='description',
            new_name='descripcion',
        ),
    ]
