# Generated by Django 4.2.1 on 2023-05-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='precio_total_bruto',
            new_name='importe_total_bruto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='precio_total_neto',
            new_name='importe_total_neto',
        ),
    ]
