# Generated by Django 4.2.1 on 2023-05-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_rename_description_articulo_descripcion'),
        ('pedido', '0002_rename_precio_total_bruto_pedido_importe_total_bruto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_en_detalle', to='articulo.articulo'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='num_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='pedido.pedido', verbose_name='Número de pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(verbose_name='Fecha de Venta'),
        ),
    ]
