# Generated by Django 4.2.1 on 2023-05-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_detallepedido_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta'),
        ),
    ]
