# Generated by Django 4.2.1 on 2023-05-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_rename_description_articulo_descripcion'),
        ('pedido', '0004_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulosEnDetalle', to='articulo.articulo'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='num_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineaPedido', to='pedido.pedido', verbose_name='Número de pedido'),
        ),
    ]
